"""
TestFileWriter for CodeShield AI.

Writes generated test suites to disk in the appropriate directory structure
for each language and framework. Handles:
- Existing test file detection (prevents overwriting)
- Import resolution
- Fixture/setup code generation
- conftest.py creation for shared fixtures
- __tests__ directory creation for JavaScript
- Maven/Gradle test directory structure for Java
- Co-located Go test files
"""

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from utils.logger import get_logger

from agents.test_generator import GeneratedTest, TestSuite

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Default paths per language/framework
# ---------------------------------------------------------------------------

DEFAULT_OUTPUT_PATHS = {
    "python": {
        "pytest": "tests",
        "file_pattern": "test_{module}.py",
        "fixture_file": "conftest.py",
    },
    "javascript": {
        "jest": "__tests__",
        "file_pattern": "{module}.test.js",
        "fixture_file": "jest.setup.js",
    },
    "typescript": {
        "jest": "__tests__",
        "file_pattern": "{module}.test.ts",
        "fixture_file": "jest.setup.ts",
    },
    "java": {
        "junit5": "src/test/java",
        "file_pattern": "{package}/{class_name}Test.java",
        "fixture_file": "TestConfig.java",
    },
    "go": {
        "go_test": ".",  # Co-located with source
        "file_pattern": "{module}_test.go",
        "fixture_file": "test_helper.go",
    },
}

# Standard conftest.py content for Python
DEFAULT_CONFTEST_PY = '''"""
Shared pytest fixtures for the test suite.

Auto-generated by CodeShield AI Test Generator.
"""

import pytest


@pytest.fixture
def temp_directory(tmp_path):
    """Provide a temporary directory for file-based tests."""
    return tmp_path


@pytest.fixture
def mock_logger():
    """Provide a mock logger for testing logging behavior."""
    from unittest.mock import MagicMock
    return MagicMock()


@pytest.fixture
def sample_user_data():
    """Provide sample user data for testing."""
    return {
        "id": 1,
        "name": "Test User",
        "email": "test@example.com",
        "role": "user",
    }


@pytest.fixture
def sample_request_context():
    """Provide a sample HTTP request context."""
    return {
        "method": "POST",
        "path": "/api/test",
        "headers": {"Content-Type": "application/json"},
        "body": {},
    }
'''

# Standard jest.setup.js content
DEFAULT_JEST_SETUP_JS = '''// Auto-generated by CodeShield AI Test Generator
// Jest setup file for shared configuration

global.__TEST__ = true;

// Increase timeout for integration tests
jest.setTimeout(10000);

// Mock console.error and console.warn to fail tests on unexpected errors
const originalError = console.error;
const originalWarn = console.warn;

console.error = (...args) => {
    if (/Warning/.test(args[0])) return;
    originalError.call(console, ...args);
};

console.warn = (...args) => {
    originalWarn.call(console, ...args);
};

// Global test utilities
global.createMockResponse = () => ({
    status: jest.fn().mockReturnThis(),
    json: jest.fn().mockReturnThis(),
    send: jest.fn().mockReturnThis(),
});
'''

# Standard Go test helper
DEFAULT_GO_TEST_HELPER = '''package main

// Auto-generated by CodeShield AI Test Generator
// Shared test utilities

import (
    "testing"
    "github.com/stretchr/testify/assert"
)

// AssertNoError is a helper that fails the test if err is not nil
func AssertNoError(t *testing.T, err error, msg ...string) {
    if len(msg) > 0 {
        assert.NoError(t, err, msg[0])
    } else {
        assert.NoError(t, err)
    }
}

// Must is a helper that fails the test if the error is not nil
func Must(t *testing.T, err error) {
    if err != nil {
        t.Fatalf("unexpected error: %v", err)
    }
}
'''


class TestFileWriter:
    """
    Writes generated test suites to disk with proper directory structure.

    Handles all supported languages and frameworks, detects existing files,
    manages imports, and creates shared fixture files.
    """

    def __init__(
        self,
        output_base: Optional[str] = None,
        overwrite: bool = False,
        create_fixtures: bool = True,
    ) -> None:
        """
        Initialize the TestFileWriter.

        Args:
            output_base: Base directory for test output. Defaults to current working directory.
            overwrite: Whether to overwrite existing test files.
            create_fixtures: Whether to create shared fixture/setup files.
        """
        self.output_base = Path(output_base or os.getcwd())
        self.overwrite = overwrite
        self.create_fixtures = create_fixtures
        self._written_files: List[str] = []
        self._skipped_files: List[str] = []

    def write_test_suite(
        self,
        suite: TestSuite,
        module_name: Optional[str] = None,
        package_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Write a single test suite to disk.

        Args:
            suite: The test suite to write
            module_name: The source module name (for file naming)
            package_name: The Java package name

        Returns:
            Dict with 'written_to', 'status', 'message'
        """
        file_path = self._get_output_path(suite, module_name, package_name)

        # Check for existing file
        if file_path.exists() and not self.overwrite:
            message = f"Test file already exists: {file_path}"
            logger.info(message)
            self._skipped_files.append(str(file_path))
            return {
                "written_to": str(file_path),
                "status": "skipped",
                "message": message,
            }

        # Ensure directory exists
        file_path.parent.mkdir(parents=True, exist_ok=True)

        # Generate the full test file content
        content = self._assemble_file_content(suite)

        # Write the file
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(content)

            self._written_files.append(str(file_path))
            message = f"Test file written: {file_path}"
            logger.info(message)

            return {
                "written_to": str(file_path),
                "status": "written",
                "message": message,
            }

        except Exception as e:
            error_msg = f"Failed to write test file {file_path}: {e}"
            logger.error(error_msg)
            return {
                "written_to": str(file_path),
                "status": "failed",
                "message": error_msg,
            }

    def write_all_suites(
        self,
        suites: List[TestSuite],
        module_name: Optional[str] = None,
        package_name: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Write all test suites to disk.

        Args:
            suites: List of test suites to write
            module_name: The source module name
            package_name: The Java package name

        Returns:
            Dict with summary of write operations
        """
        results: List[Dict[str, Any]] = []

        for suite in suites:
            result = self.write_test_suite(suite, module_name, package_name)
            results.append(result)

        # Create fixture files if enabled
        fixture_results: List[Dict[str, Any]] = []
        if self.create_fixtures:
            fixture_results = self._create_fixture_files(suites)

        written = [r for r in results if r["status"] == "written"]
        skipped = [r for r in results if r["status"] == "skipped"]
        failed = [r for r in results if r["status"] == "failed"]

        return {
            "total_suites": len(suites),
            "written": len(written),
            "skipped": len(skipped),
            "failed": len(failed),
            "results": results,
            "fixture_results": fixture_results,
            "written_files": self._written_files,
            "skipped_files": self._skipped_files,
        }

    def _get_output_path(
        self,
        suite: TestSuite,
        module_name: Optional[str] = None,
        package_name: Optional[str] = None,
    ) -> Path:
        """
        Determine the output file path for a test suite.

        Args:
            suite: The test suite
            module_name: Source module name
            package_name: Java package name

        Returns:
            Path object for the output file
        """
        lang = suite.language
        framework = suite.framework

        config = DEFAULT_OUTPUT_PATHS.get(lang, {})
        base_dir = self.output_base

        if lang in ("python",):
            test_dir = base_dir / config.get("pytest", "tests")
            file_name = config["file_pattern"].format(
                module=module_name or suite.target_name.lower()
            )
            return test_dir / file_name

        elif lang in ("javascript", "typescript"):
            test_dir = base_dir / config.get("jest", "__tests__")
            file_name = config["file_pattern"].format(
                module=module_name or suite.target_name.lower()
            )
            return test_dir / file_name

        elif lang == "java":
            test_dir = base_dir / config.get("junit5", "src/test/java")
            pkg = package_name or "com.example"
            pkg_dir = test_dir / pkg.replace(".", "/")
            file_name = config["file_pattern"].format(
                package=pkg.replace(".", "/"),
                class_name=suite.target_name,
            )
            return pkg_dir / f"{suite.target_name}Test.java"

        elif lang == "go":
            # Go tests are co-located with source
            test_dir = base_dir
            file_name = config["file_pattern"].format(
                module=module_name or suite.target_name.lower()
            )
            return test_dir / file_name

        # Default fallback
        return base_dir / f"test_{suite.target_name}.py"

    def _assemble_file_content(self, suite: TestSuite) -> str:
        """
        Assemble the complete test file content with proper headers.

        Args:
            suite: The test suite

        Returns:
            Complete file content as string
        """
        lines: List[str] = []

        # Add auto-generated header
        lines.append(f"# Auto-generated by CodeShield AI Test Generator")
        lines.append(f"# Target: {suite.target_name}")
        lines.append(f"# Language: {suite.language}")
        lines.append(f"# Framework: {suite.framework}")
        lines.append(f"# Tests: {len(suite.tests)}")
        lines.append("")

        # Add imports
        if suite.imports:
            for imp in suite.imports:
                lines.append(imp)
            lines.append("")

        # Add fixture imports from tests
        fixture_imports: Set[str] = set()
        for test in suite.tests:
            for imp in test.imports_needed:
                if imp not in ("hypothesis", "hypothesis.strategies as st"):
                    fixture_imports.add(imp)

        if "hypothesis" in str(test.imports_needed for test in suite.tests):
            lines.append("from hypothesis import given, strategies as st, settings")
            lines.append("")

        # Add any additional fixture imports
        for imp in sorted(fixture_imports):
            if imp == "unittest.mock":
                lines.append("from unittest.mock import patch, MagicMock, AsyncMock, Mock")
            elif imp == "pytest_asyncio":
                lines.append("import pytest_asyncio")
            else:
                lines.append(f"import {imp}")
        if fixture_imports:
            lines.append("")

        # Add fixtures
        if suite.fixtures:
            for fixture_name, fixture_code in suite.fixtures.items():
                lines.append(fixture_code)
                lines.append("")

        # Add setup code
        if suite.setup_code:
            lines.append(suite.setup_code)
            lines.append("")

        # Add tests
        for test in suite.tests:
            lines.append(test.test_code)
            lines.append("")

        return "\n".join(lines)

    def _create_fixture_files(
        self,
        suites: List[TestSuite],
    ) -> List[Dict[str, Any]]:
        """
        Create shared fixture/setup files if they don't exist.

        Args:
            suites: All test suites being written

        Returns:
            List of fixture creation results
        """
        results: List[Dict[str, Any]] = []
        languages = {suite.language for suite in suites}

        for lang in languages:
            result = self._create_fixture_for_language(lang)
            if result:
                results.append(result)

        return results

    def _create_fixture_for_language(
        self,
        language: str,
    ) -> Optional[Dict[str, Any]]:
        """Create fixture file for a specific language."""
        config = DEFAULT_OUTPUT_PATHS.get(language)
        if not config:
            return None

        if language == "python":
            return self._create_conftest_py()
        elif language in ("javascript", "typescript"):
            return self._create_jest_setup(language)
        elif language == "go":
            return self._create_go_test_helper()

        return None

    def _create_conftest_py(self) -> Dict[str, Any]:
        """Create conftest.py for Python/pytest projects."""
        conftest_path = self.output_base / "tests" / "conftest.py"

        if conftest_path.exists() and not self.overwrite:
            return {
                "file": str(conftest_path),
                "status": "skipped",
                "message": "conftest.py already exists",
            }

        conftest_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            with open(conftest_path, "w", encoding="utf-8") as f:
                f.write(DEFAULT_CONFTEST_PY)

            self._written_files.append(str(conftest_path))
            return {
                "file": str(conftest_path),
                "status": "written",
                "message": "Created conftest.py with shared fixtures",
            }
        except Exception as e:
            return {
                "file": str(conftest_path),
                "status": "failed",
                "message": f"Failed to create conftest.py: {e}",
            }

    def _create_jest_setup(self, language: str) -> Dict[str, Any]:
        """Create Jest setup file for JavaScript/TypeScript projects."""
        ext = "ts" if language == "typescript" else "js"
        setup_path = self.output_base / f"jest.setup.{ext}"
        config_path = self.output_base / "jest.config.js"

        result = {"files": []}

        # Write setup file
        if not setup_path.exists() or self.overwrite:
            try:
                setup_path.parent.mkdir(parents=True, exist_ok=True)
                with open(setup_path, "w", encoding="utf-8") as f:
                    if language == "typescript":
                        f.write(DEFAULT_JEST_SETUP_JS.replace(".js", ".ts"))
                    else:
                        f.write(DEFAULT_JEST_SETUP_JS)
                self._written_files.append(str(setup_path))
                result["files"].append(str(setup_path))
            except Exception as e:
                logger.error("Failed to create jest setup: %s", e)

        # Write jest config if needed
        if not config_path.exists():
            try:
                config_content = f"""module.exports = {{
    setupFilesAfterEnv: ['<rootDir>/jest.setup.{ext}'],
    testEnvironment: 'node',
    testMatch: ['**/__tests__/**/*.test.{ext}'],
    collectCoverageFrom: ['**/*.{ext}', '!**/*.test.{ext}', '!**/node_modules/**'],
}};"""
                with open(config_path, "w", encoding="utf-8") as f:
                    f.write(config_content)
                self._written_files.append(str(config_path))
                result["files"].append(str(config_path))
            except Exception as e:
                logger.error("Failed to create jest config: %s", e)

        return {
            "file": str(setup_path),
            "status": "written",
            "message": f"Created Jest setup files for {language}",
            "details": result,
        }

    def _create_go_test_helper(self) -> Dict[str, Any]:
        """Create Go test helper file."""
        helper_path = self.output_base / "test_helper.go"

        if helper_path.exists() and not self.overwrite:
            return {
                "file": str(helper_path),
                "status": "skipped",
                "message": "test_helper.go already exists",
            }

        try:
            with open(helper_path, "w", encoding="utf-8") as f:
                f.write(DEFAULT_GO_TEST_HELPER)

            self._written_files.append(str(helper_path))
            return {
                "file": str(helper_path),
                "status": "written",
                "message": "Created test_helper.go with utilities",
            }
        except Exception as e:
            return {
                "file": str(helper_path),
                "status": "failed",
                "message": f"Failed to create test_helper.go: {e}",
            }

    def check_existing_tests(
        self,
        suite: TestSuite,
        module_name: Optional[str] = None,
        package_name: Optional[str] = None,
    ) -> bool:
        """
        Check if a test file already exists for the given suite.

        Args:
            suite: The test suite
            module_name: Source module name
            package_name: Java package name

        Returns:
            True if the test file already exists
        """
        file_path = self._get_output_path(suite, module_name, package_name)
        return file_path.exists()

    def get_written_files(self) -> List[str]:
        """Return list of files that were written."""
        return self._written_files

    def get_skipped_files(self) -> List[str]:
        """Return list of files that were skipped (already exist)."""
        return self._skipped_files

    def generate_summary(self) -> str:
        """Generate a human-readable summary of write operations."""
        lines = [
            "=" * 60,
            "CodeShield AI - Test File Generation Summary",
            "=" * 60,
            f"Written files ({len(self._written_files)}):",
        ]
        for f in self._written_files:
            lines.append(f"  + {f}")

        if self._skipped_files:
            lines.append(f"\nSkipped files ({len(self._skipped_files)}) - already exist:")
            for f in self._skipped_files:
                lines.append(f"  - {f}")

        lines.append("")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------

def write_test_suites(
    suites: List[TestSuite],
    output_base: Optional[str] = None,
    overwrite: bool = False,
    create_fixtures: bool = True,
) -> Dict[str, Any]:
    """
    Convenience function to write test suites without instantiating TestFileWriter.

    Args:
        suites: List of test suites to write
        output_base: Base directory for output
        overwrite: Whether to overwrite existing files
        create_fixtures: Whether to create shared fixture files

    Returns:
        Dict with summary of write operations
    """
    writer = TestFileWriter(
        output_base=output_base,
        overwrite=overwrite,
        create_fixtures=create_fixtures,
    )
    return writer.write_all_suites(suites)
